### ISSUE TITLE
works only about 1/10 times.

### ISSUE THREAD

**Issue by Boolman** [vmware/cloud-init-vmware-guestinfo#34]
When im testing this out, it works flawless about 1/10th of the time.
other times it either partially works, eg. 
* configures the username but it seems the networking hasnt been setup yet. after a cloud-init clean && cloud-init init this usually works.
* doesnt even fetch the metadata+userdata 

vcenter version: 6.7
Compatibility:	ESXi 6.7 and later (VM version 14)
Hypervisor:	VMware ESXi, 6.7.0, 14320388
open-vm-tools 2:11.0.1-2ubuntu0.18.04.2
cloud-init 19.4-33-gbb4131a2-0ubuntu1~18.04.1
ubuntu bionic 18.04.4

  extra_config = {
    "guestinfo.userdata": base64encode(file("userdata.yaml")),
    "guestinfo.userdata.encoding": "base64",
    "guestinfo.metadata.encoding": "base64",
    "guestinfo.metadata": base64encode(file("metadata.yaml"))
  }

```yaml
instance-id: test0123
local-hostname: test123
network:
  version: 2
  ethernets:
    ens160:
      nameservers:
        addresses: [8.8.8.8]
      match:
        name: ens160
      set-name: ens160
      dhcp4: no
      addresses: [ 10.1.25.171/24 ]
      gateway4: 10.1.25.1
```

```yaml
#cloud-config
manage_etc_hosts: true
package_update: true
package_upgrade: true
package_reboot_if_required: true
timezone: Europe/Stockholm
users:
- name: ubuntu 
  plain_text_passwd: 'Password'
  home: /home/ubuntu
  shell: /bin/bash
  gecos: Ubuntu
  lock_passwd: false
  groups: [adm, sudo] 
  sudo: ALL=(ALL) NOPASSWD:ALL
output: {all: '| tee -a /var/log/cloud-init-output.log'}
```
