### ISSUE TITLE
Terraform vsphere guestinfo.metadata issue

### ISSUE THREAD

**Issue by dciancio** [vmware/cloud-init-vmware-guestinfo#39]
~~~
# terraform version
Terraform v0.12.24
+ provider.local v1.4.0
+ provider.template v2.1.2
+ provider.vsphere v1.17.0

# rpm -qa | egrep "open-vm-tools|cloud-init|guestinfo" | sort
cloud-init-18.5-6.el7.x86_64
cloud-init-vmware-guestinfo-1.1.0-1.el7.noarch
open-vm-tools-10.3.10-2.el7.x86_64
~~~
Configured cloud-init-vmware-guestinfo in /etc/cloud/cloud.cfg.d to read guestinfo datasource as follows:
~~~
# cat /etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg 

# Cloud-Init Datasource for VMware Guestinfo
#
# Copyright (c) 2018 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Apache 2.0 license (the "License").
# You may not use this product except in compliance with the Apache 2.0 License.
#
# This product may include a number of subcomponents with separate copyright
# notices and license terms. Your use of these subcomponents is subject to the
# terms and conditions of the subcomponent's license, as noted in the LICENSE
# file.

datasource_list: [ "VMwareGuestInfo" ]

~~~
Here is extra_config block defined in Terraform resource "vsphere_virtual_machine" :
~~~
  extra_config = {
    "guestinfo.userdata"          = "${var.userdata}"
    "guestinfo.userdata.encoding" = "gzip+base64"
    "guestinfo.metadata"          = <<-EOT
{
  "local-hostname": "${var.name}-${count.index}.${var.cluster_domain}",
  "instance-id": "${var.name}-${count.index}.${var.cluster_domain}",
  "network": {
    "version": 2,
    "ethernets": {
      "eth0": {
        "dhcp4": false,
        "addresses": [
          "${var.ip_addresses[count.index]}/${var.netmask}"
        ],
        "gateway4": "${var.gateway}",
        "nameservers": {
          "search": [
            "${var.cluster_domain}"
          ],
          "addresses": [
            "${var.dns}"
          ]
        }
      }
    }
  }
}
EOT
~~~
Both guestinfo.metadata and guestinfo.userdata are read in fine:
~~~
# vmware-rpctool "info-get guestinfo.metadata"
{
  "local-hostname": "bastion-0.ddcocp311.tamlab.brq.redhat.com",
  "instance-id": "bastion-0.ddcocp311.tamlab.brq.redhat.com",
  "network": {
    "version": 2,
    "ethernets": {
      "eth0": {
        "dhcp4": false,
        "addresses": [
          "10.37.198.140/25"
        ],
        "gateway4": "10.37.198.254",
        "nameservers": {
          "search": [
            "ddcocp311.tamlab.brq.redhat.com"
          ],
          "addresses": [
            "10.37.197.1"
          ]
        }
      }
    }
  }
}
~~~
Userdata consists of a multi-part (cloud-config + bash shell script).
~~~
# vmware-rpctool "info-get guestinfo.userdata" | base64 -d | gunzip
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config

ssh_authorized_keys:
  - ssh-rsa .... <redacted>

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

#!/usr/bin/env bash

.... <redacted>

--MIMEBOUNDARY--
~~~
The userdata is applied successfully to the system.

The issue is applying the static network information (above).  It's successfully read in but not applied.  The ifcfg-eth0 file is still set to dhcp as follows:
~~~
# cat /etc/sysconfig/network-scripts/ifcfg-eth0
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=dhcp
DEVICE=eth0
HWADDR=00:50:56:8f:25:94
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
~~~
The guestinfo documentation states that network config v2 is supported.  

What am I missing or doing wrong here?

**Comment by oulman** [comment]
From my understanding in 1.1.0 you need to base64 encode and wrap the cloud-init network config in JSON. The example in master is for 1.3.X which accepts YAML directly.

There is an example in the 1.1.0 [README.md](https://github.com/vmware/cloud-init-vmware-guestinfo/blob/v1.1.0/README.md)

Here is what I am doing in 1.1.0

```
  extra_config = {
    "guestinfo.metadata"          = base64encode(templatefile("${path.module}/templates/metadata.json.tpl", {
      name = var.vm_name

      network_config = base64encode(templatefile("${path.module}/templates/network.tpl", {
        ipv4_subnet_mask = var.ipv4_subnet_mask
        ipv4  = var.ipv4_addr
        ipv4_gateway = var.ipv4_gateway
      }))
    }))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/cloud-config/centos7.yaml"))
    "guestinfo.userdata.encoding" = "base64"
  }
}
```
metadata.json.tpl

```
{
  "network": "${network_config}",
  "network.encoding": "base64",
  "local-hostname": "${name}",
  "instance-id": "${name}"
}
```

network.tpl

```
version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        address: ${ipv4}/${ipv4_subnet_mask}
        gateway: ${ipv4_gateway}
        dns_nameservers:
          - 8.8.8.8
          - 1.1.1.1
        dns_search:
          - mydomain.com
```

**Comment by JerrodCarpenter** [comment]
I'm having the same issue, no matter what I try, it always configures it for DHCP.

_Edit: I set up my metadata to be a yaml file as described in the wiki and still having the same issue_

```
# vmware-rpctool "info-get guestinfo.metadata" | base64 -d | gunzip
---
network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
    - type: static
      address: 1.2.3.4
      netmask: 255.255.254.0
      gateway: 1.2.3.1
      dns_nameservers:
      - 1.14.226.153
      - 1.14.232.5
      dns_search:
      - dns.com
```

**Comment by oulman** [comment]
I am using v1 syntax with 1.1.0 and got it working. 

The [v1.1.0 README.md](https://github.com/vmware/cloud-init-vmware-guestinfo/blob/v1.1.0/README.md) states that you have to wrap the network config in json. 

Here is my Terraform extra.config

``` hcl
  extra_config = {
    "guestinfo.metadata" = base64encode(templatefile("${path.module}/templates/metadata.json.tpl", {
      name = var.vm_name

      network_config = base64encode(templatefile("${path.module}/templates/network.tpl", {
        ipv4_subnet_mask = var.ipv4_subnet_mask
        ipv4             = var.ipv4
        ipv4_gateway     = var.ipv4_gateway
      }))
    }))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/cloud-config/centos7.yaml"))
    "guestinfo.userdata.encoding" = "base64"
  }
```
network.tpl

``` yaml
version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        address: ${ipv4}/${ipv4_subnet_mask}
        gateway: ${ipv4_gateway}
        dns_nameservers:
          - 8.8.8.8
        dns_search:
          - mycompany.com
```
metadata.json.tpl


``` json
{
  "network": "${network_config}",
  "network.encoding": "base64",
  "local-hostname": "${name}",
  "instance-id": "${name}"
}
```
