### ISSUE TITLE
VMware vCloudDirector

### ISSUE THREAD

**Issue by iggyshu** [vmware/cloud-init-vmware-guestinfo#60]
Please correct me if I am wrong and this is not meant to work with vCloudDirector. I see that all examples are based on vSphere.

## Expected Behavior
The data source pulls userdata/metadata from guest properties of a VM in vcd and is selected by cloud-init.

## Actual Behavior
The data source is recognized by cloud-init, but data is not pulled from guest properties. Cloud-init proceeds using default configuration files (data source none).

## Steps to Reproduce

The following setup:
* vCloud Director version: 10.0.0.15449638
* Ubuntu Live Server 20.04.1
  * Custom .ova template prepared with Packer
  * open-vm-tools package is installed
  * vmware-guestinfo is installed using install.sh script

The steps:
1. Provision a vApp with 1 VM in vcd using Terraform v0.13.2
2. Supply userdata/metadata to VM, tried:
```
  guest_properties = {
    "metadata" = base64encode("# empty")
    "metadata.encoding" = "base64"
    "userdata" = base64encode(data.template_file.ubuntu-userdata.rendered)
    "userdata.encoding" = "base64"
  }
```
or:
```
  guest_properties = {
    "guestinfo.metadata" = base64encode("# empty")
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata" = base64encode(data.template_file.ubuntu-userdata.rendered)
    "guestinfo.userdata.encoding" = "base64"
  }
```
Example userdata file:
```
#cloud-config
network:
  version: 2
  ethernets:
    id0:
      match:
        name: ens*
      dhcp4: false
      addresses:
        - ${address}
      gateway4: ${gateway}
      nameservers:
        addresses:
          - ${dns}
instance-id: ${computername}
local-hostname: ${computername}
users:
  - default
  - name: ${username}
    groups: users, admin
    lock_passwd: false
    passwd: ${passwd}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
```
3. After creation, login to VM through VM Remote Console, check `/var/log/cloud-init.log`
4. See that, although the vmware-guestinfo data source is recognized, cloud-init proceeds with data source none:

![image](https://user-images.githubusercontent.com/27514711/95177985-27a1df80-07bf-11eb-9943-934023567073.png)

**Comment by gevraud** [comment]
Hi,

I feel I have the same issue. 

I added the 99-DataSourceVMwareGuestInfo.cfg  in cloud.cfg.d directory in the VM template.

First boot , the datasource is detected but nothing is done (even if user-data is present in guest properties)

If I do sudo cloud-init clean && sudo cloud-init init, it read the guest-properties and applies it.

But that's not a real solution..

Regards

**Comment by akutz** [comment]
I have not tried this with Terraform, or with vCD. However, I will say the data in the description is incorrect. There should be two, distinct sets of data:

**metadata**
```yaml
network:
  version: 2
  ethernets:
    id0:
      match:
        name: ens*
      dhcp4: false
      addresses:
        - ${address}
      gateway4: ${gateway}
      nameservers:
        addresses:
          - ${dns}
instance-id: ${computername}
local-hostname: ${computername}
```

**userdata**
```yaml
#cloud-config
users:
  - default
  - name: ${username}
    groups: users, admin
    lock_passwd: false
    passwd: ${passwd}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
```

The [_Walkthrough_](https://github.com/vmware/cloud-init-vmware-guestinfo#walkthrough) section of the docs illustrates what goes in the metadata versus the userdata. 

Can you try that instead?
